# Thiết lập cho DiscordSRV
# Cần trợ giúp? Tham gia Discord của  chúng tôi, https://discordsrv.com/discord

# Làm ơn đừng đụng vào dòng này
ConfigVersion: ${project.version}

# Bot token; không biết đây là gì ư? Để biết thêm chi tiết hãy xem video hướng dẫn trên trang plugin DiscordSRV
# Bạn phải khởi động lại máy chủ để xác nhận thay đổi BotToken
BotToken: "BOTTOKEN"

# Kết nối chat trong game với Discord
# Từ khóa là Channels: {"Tên kênh chat trong Minecraft": "Mã số kênh trong Discord", "Một tên kênh chat trong Minecraft khác": "Một mã số kênh Discord khác"}
#
# Tất cả tin nhắn của DiscordSRV sẽ được chuyển tới kênh đầu tiên trừ khi có một kênh cho loại tin nhắn đó được đưa ra:
# khi sử dụng một plugin chat được hỗ trợ, tên kênh sẽ là tên do plugin đó đặt (cho tin nhắn)
#  - Nếu bạn đang sử dụng plugin TownyChat, tên kênh mặc định thường được gọi là "general" thay vì "global"
# Cho tin nhắn chat mặc định (Khi không sử dụng plugin chat nào): global
# Dành cho thông báo máy chủ Bật/Tắt: status
# Dành cho thông báo Thành Tựu/Tiến trình: awards
# Dành cho thông báo chết: deaths
# Dành cho thông báo tham gia trò chơi: join
# Dành cho thông báo rời trò chơi: leave
# Dành cho tin nhắn trong dynmap: dynmap
# Dành cho tin nhắn watchdog: watchdog
# Dành cho /discord broadcast: broadcasts (unless specified in the command)
#
# Phần đầu tiên trong cặp ngoặc nhọn Channels này không phải tên kênh Discord!
# Bạn phải khởi động lại máy chủ để xác nhận thay đổi Channels
Channels: {"global": "000000000000000000"}

# Mã ID kênh dành cho discord Console (KHÔNG PHẢI TÊN), Bỏ trống để tắt chuyển tin console
DiscordConsoleChannelId: "000000000000000000"

# Đường dẫn mời discord khi bật tính năng bắt người chơi phải liên kết Discord
DiscordInviteLink: "https://discord.gg/thay-đổi-dòng-này-trong-config.yml"

# Thông tin gỡ lỗi
# Đừng bặt tính năng này trừ khi bạn đang cố tìm lỗi.
#
# Danh mục Debug hiện có:
# MINECRAFT_TO_DISCORD  - Tin nhắn tới từ Minecraft
# DISCORD_TO_MINECRAFT  - Tin nhắn tới từ Discord
# GROUP_SYNC            - Đồng bộ theo nhóm
# PRESENCE              - Status hoặc Presence của con Bot
# VOICE                 - Hệ thống voice chat (Hãy xem voice.yml)
# REQUIRE_LINK          - Liên kết cần thiết cho hệ thống liên kết (Hãy xem linking.yml)
# NICKNAME_SYNC         - Đồng bộ Tên Đệm
# ALERTS                - Cảnh báo (Hãy xem alerts.yml)
# WATCHDOG              - Watchdog
# BAN_SYNCHRONIZATION   - Đồng bộ Ban (Cấm)
# LP_CONTEXTS           - Viễn cảnh của LuckPerm (LuckPerm's contexts)
# ACCOUNT_LINKING       - liên kết tài khoản giữa Discord/Minecraft 
#
# UNCATEGORIZED         - Bất cứ thứ gì không ở trong danh mục trên
# ALL                   - Tất cả danh mục trên (Bao gồm cả UNCATEGORIZED)
#
# JDA                   - Thông báo gỡ lỗi của JDA
# JDA_REST_ACTIONS      - Để gỡ lỗi thông báo nghỉ của JDA
# CALLSTACKS            - Hiển thị stack trace cho DiscordSRV debug calls
#
# Ví dụ. "Debug: [GROUP_SYNC, PRESENCE]"
#
Debug: []

# Lựa chọn phụ để chuyển dần qua các lựa chọn gỡ lỗi mới,
# Chuyển dòng này thành 1 tương tự như đặt lựa chọn gỡ lỗi là [ALL]
DebugLevel: 0

# Thử nghiệm
# Những tính năng này hoàn toàn chưa được tối ưu hóa; Sử Dụng Cẩn Thận.

# JDBC (MySQL/MariaDB)
Experiment_JdbcAccountLinkBackend: "jdbc:mysql://HOST:PORT/DATABASE?autoReconnect=true&useSSL=false"
Experiment_JdbcTablePrefix: "discordsrv"
Experiment_JdbcUsername: "username"
Experiment_JdbcPassword: "password"

# Webhook Delivery
Experiment_WebhookChatMessageDelivery: false
Experiment_WebhookChatMessageUsernameFormat: "%displayname%"
Experiment_WebhookChatMessageFormat: "%message%"
Experiment_WebhookChatMessageUsernameFromDiscord: false
Experiment_WebhookChatMessageAvatarFromDiscord: false

# Định dạng Embed và webhook cho hình ảnh/avatar
# Đường dẫn avatar thay thế cho máy chủ cracked:
# https://cravatar.eu/helmavatar/{username}/{size}.png#{texture}
AvatarUrl: https://crafatar.com/avatars/{uuid-nodashes}.png?size={size}&overlay#{texture}

# Reserializer
# Chuyển đổi định dạng (in hoa, in nghiêng, gạch chân, gạch giữa chữ) giữa Minecraft và Discord
Experiment_MCDiscordReserializer_ToDiscord: false
Experiment_MCDiscordReserializer_ToMinecraft: false
Experiment_MCDiscordReserializer_InBroadcast: false

# Các thứ khác
CancelConsoleCommandIfLoggingFailed: true
ForcedLanguage: none
PrintGuildsAndChannels: true
ForceTLSv12: true
NoopHostnameVerifier: false
MaximumAttemptsForSystemDNSBeforeUsingFallbackDNS: 3
TimestampFormat: EEE, d. MMM yyyy HH:mm z
DateFormat: dd-MM-yyyy
# https://github.com/DiscordSRV/DiscordSRV/wiki/config#Timezone
Timezone: Etc/GMT+7

# Nối Plugin
# Bạn phải khởi động lại máy chủ sau khi chỉnh những lựa chọn này
#
# DisabledPluginHooks: Các kết nối plugin sẽ không được sử dụng (Bình thường sẽ chỉ là tên của Plugin).
# VentureChatBungee: Bật kết nối VentureChat cho các tính năng của BungeeCord (Tin nhắn được nhận từ tất cả các máy chủ, yêu cầu ít nhất 1 người chơi trực tuyến)
# EnablePresenceInformation: Bật thông tin presence, sẽ cần giữ chỗ cho PlaceholderAPI. Lưu ý rằng điều này cần bật tính năng "Presence Intent" trên Discord developer portal
# UseModernPaperChatEvent: chỉ sử dụng tính năng này nếu bạn có plugin chat Mà ĐẶC BIỆT TỐI ƯU TÍNH NĂNG "AsyncChatEvent" của Paper
DisabledPluginHooks: []
VentureChatBungee: false
EnablePresenceInformation: false
UseModernPaperChatEvent: false

# Thông Tin Game
# Đặt thông báo "Playing: ______" cho Bot.
# Có thể là một giá trị đơn hoặc tĩnh, hoặc đi qua nhiều lựa chọn
# Bạn có thể thay Status với "playing", "watching", hoặc "listening to" để đặt loại hành động
# Giữ chỗ cho PlaceholderAPI được hỗ trợ
#
# DiscordGameStatus: Chữ để hiển thị. Có thể là một từ VD. "Minecraft", Hoặc nhiều từ VD. ["Minecraft", "IPcủabạn.thayđổitôi.com"]
# StatusUpdateRateInMinutes: Tỉ lệ cập nhật Status mỗi bao nhiêu phút
DiscordGameStatus: "Máy chủ Minecraft"
StatusUpdateRateInMinutes: 2

# Thông tin kênh chat
# Kênh chat là kênh chứ mà tất cả tin nhắn trong game sẽ được gửi tới và tất cả tin nhắn được gửi
# tới kênh này trên Discord sẽ được gửi vào trong game
#
# DiscordChatChannelDiscordToMinecraft: Khi nào nên hoặc không nên truyền tin từ Discord tới Kênh chat của Máy chủ
# DiscordChatChannelMinecraftToDiscord: Khi nào nên hoặc không nên truyền tin từ kênh chat của máy chủ tới Discord
# DiscordChatChannelTruncateLength: Độ dài tối đa của tin nhắn gửi từ Discord tới Minecraft
# DiscordChatChannelTranslateMentions: Khi nào nên hoặc không nên dịch lời nhắc tới @AiĐó từ Minecraft tới kênh Discord
# DiscordChatChannelAllowedMentions: Các loại lời nhắc được phép gửi từ Minecraft tới Discord; các loại còn thiếu trong giá trị mặc định là "@role", "@here", "@everyone."
# DiscordChatChannelEmojiBehavior: how emojis should be sent to Minecraft. Can be "show", "name" or "hide"
# DiscordChatChannelEmoteBehavior: how emotes should be sent to Minecraft. Can be "name" or "hide"
# DiscordChatChannelPrefixRequiredToProcessMessage: the character(s) required to prefix a message for it to be sent from Minecraft to Discord (example "!")
# DiscordChatChannelRolesAllowedToUseColorCodesInChat: list of roles allowed to use color/format codes in Discord to Minecraft chat
# DiscordChatChannelBroadcastDiscordMessagesToConsole: whether or not to print processed discord messages to the console
# DiscordChatChannelRequireLinkedAccount: whether or not to require players have their Discord account linked to their Minecraft to have their Discord messages sent to Minecraft
# DiscordChatChannelBlockBots: whether or not bots should be blocked from Discord -> MC chat
# DiscordChatChannelBlockedIds: ids of discord users (or bots) that should not have their messages processed & sent to MC
# DiscordChatChannelRolesSelectionAsWhitelist: if the following list should be treated as a whitelist (true) or a blacklist (false)
# DiscordChatChannelRolesSelection: list of roles that should be filtered from all of a user's roles
# DiscordChatChannelRoleAliases: list of role aliases (alternate names for roles to use in Minecraft messages)
#
DiscordChatChannelDiscordToMinecraft: true
DiscordChatChannelMinecraftToDiscord: true
DiscordChatChannelTruncateLength: 256
DiscordChatChannelTranslateMentions: true
DiscordChatChannelAllowedMentions: [user, channel, emote]
DiscordChatChannelEmojiBehavior: "name"
DiscordChatChannelEmoteBehavior: "name"
DiscordChatChannelPrefixRequiredToProcessMessage: ""
DiscordChatChannelRolesAllowedToUseColorCodesInChat: ["Developer", "Owner", "Admin", "Moderator"]
DiscordChatChannelBroadcastDiscordMessagesToConsole: true
DiscordChatChannelRequireLinkedAccount: false
DiscordChatChannelBlockBots: false
DiscordChatChannelBlockedIds: ["000000000000000000", "000000000000000000", "000000000000000000"]
DiscordChatChannelRolesSelectionAsWhitelist: false
DiscordChatChannelRolesSelection: ["Don't show me!", "Misc role"]
DiscordChatChannelRoleAliases: {"Developer": "Dev"}

# Console channel information
# The console channel is the text channel that receives messages which are then run as server commands
# by the console as well as having the server's console being streamed to line by line
#
# You can customize the message including removing timestamps in messages.yml
#
# DiscordConsoleChannelLogRefreshRateInSeconds: rate in seconds between sending lines from the console
# DiscordConsoleChannelUsageLog:
#    %date%:  current date
#              example: 2017-01-01
#    PlaceholderAPI placeholders are supported
# DiscordConsoleChannelBlacklistActsAsWhitelist: whether or not the blacklisted commands list acts as a whitelist instead of blacklist
# DiscordConsoleChannelBlacklistedCommands: phrases wrapped in quotation marks that users should not be able to send as commands to the console
# DiscordConsoleChannelFilters: regex filters to be applied to console lines being sent to Discord, if the result is empty the message won't be sent at all
# DiscordConsoleChannelLevels: levels to send to console channel via appender
# DiscordConsoleChannelAllowPluginUpload: should uploading plugins to the console channel add them to the server automatically
#
DiscordConsoleChannelLogRefreshRateInSeconds: 5
DiscordConsoleChannelUsageLog: "Console-%date%.log"
DiscordConsoleChannelBlacklistActsAsWhitelist: false
DiscordConsoleChannelBlacklistedCommands: ["?", "op", "deop", "execute"]
DiscordConsoleChannelFilters: {".*(?i)async chat thread.*": "", ".*There are \\d+ (?:of a max of|out of maximum) \\d+ players online.*": ""}
DiscordConsoleChannelLevels: [info, warn, error]
DiscordConsoleChannelAllowPluginUpload: false

# Chat channel command execute command
# These options control the ability to say "!c kick Notch", or whatever the prefix is to run a command,
# as the console, from a registered chat channel.
#
# DiscordChatChannelConsoleCommandEnabled: whether or not to allow console commands from a chat channel.
# DiscordChatChannelConsoleCommandNotifyErrors: whether or not to send a user who tries to run a command without permission that they don't have permission
# DiscordChatChannelConsoleCommandPrefix: prefix to use for console commands. e.g. "!c tps"
# DiscordChatChannelConsoleCommandRolesAllowed: the user roles that are allowed to execute server commands from the chat channel
# DiscordChatChannelConsoleCommandWhitelist: list of commands that are able to be ran with DiscordChatChannelConsoleCommandPrefix
# DiscordChatChannelConsoleCommandWhitelistBypassRoles: list of roles that bypass the whitelist
# DiscordChatChannelConsoleCommandWhitelistActsAsBlacklist: should the command whitelist act as a blacklist instead
# DiscordChatChannelConsoleCommandExpiration: time in seconds until a sent command output is automatically removed by the bot. set to 0 to disable expiration.
# DiscordChatChannelConsoleCommandExpirationDeleteRequest: whether or not to delete the message of the person that originally issued the command
#
DiscordChatChannelConsoleCommandEnabled: true
DiscordChatChannelConsoleCommandNotifyErrors: true
DiscordChatChannelConsoleCommandPrefix: "!c"
DiscordChatChannelConsoleCommandRolesAllowed: ["Developer", "Owner"]
DiscordChatChannelConsoleCommandWhitelist: ["say", "lag", "tps"]
DiscordChatChannelConsoleCommandWhitelistBypassRoles: ["Owner", "Developer"]
DiscordChatChannelConsoleCommandWhitelistActsAsBlacklist: false
DiscordChatChannelConsoleCommandExpiration: 0
DiscordChatChannelConsoleCommandExpirationDeleteRequest: true

# Chat channel player list command
# All the config stuff for the player list command
#
# DiscordChatChannelListCommandEnabled: whether the command is enabled
# DiscordChatChannelListCommandMessage: the command people can type to get the player list
# DiscordChatChannelListCommandExpiration: time in seconds until a sent player list message is automatically removed by the bot. set to 0 to disable expiration.
# DiscordChatChannelListCommandExpirationDeleteRequest: whether or not to delete the message of the person that originally requested for the player list
#
DiscordChatChannelListCommandEnabled: true
DiscordChatChannelListCommandMessage: "playerlist"
DiscordChatChannelListCommandExpiration: 10
DiscordChatChannelListCommandExpirationDeleteRequest: true

# Chat channel blacklisted phrases & regex
#
# DiscordChatChannelGameFilters: regex filters to be applied to chat messages being sent to Discord, if the result is empty the message won't be sent at all
# DiscordChatChannelDiscordFilters: regex filters to be applied to chat messages being sent to Minecraft, if the result is empty the message won't be sent at all
#
DiscordChatChannelGameFilters: {}
DiscordChatChannelDiscordFilters: {".*Online players\\(.*": "", ".*\\*\\*No online players\\*\\*.*": ""}

# Channel topic updater settings
#
# ChannelTopicUpdaterChannelTopicsAtShutdownEnabled: whether or not the channel topics should be changed at server shutdown at all
# ChannelTopicUpdaterRateInMinutes: amount of minutes between automatically updating the channel topics with fresh information
#
ChannelTopicUpdaterChannelTopicsAtShutdownEnabled: true
ChannelTopicUpdaterRateInMinutes: 10

# Discord canned responses
# These are triggers (commands in a way) that will trigger a "canned response" to be sent as a reply to them
# You should probably change these from their defaults or add your own
#
# Syntax is {"TRIGGER": "RESPONSE", "TRIGGER": "RESPONSE", ...}
# If you do not want any canned responses, set this to just {}
# PlaceholderAPI placeholders are supported for the values
#
DiscordCannedResponses: {"!ip": "yourserveripchange.me", "!site": "http://yoursiteurl.net"}

# Minecraft to Discord account linking
# These are the options pertaining to how linking a Minecraft account to a Discord account functions
#
# MinecraftDiscordAccountLinkedConsoleCommands: commands to run when an account is linked, see below for possible placeholders
# MinecraftDiscordAccountUnlinkedConsoleCommands: commands to run when an account is unlinked, see below for possible placeholders
# %minecraftplayername%: player's Minecraft username
#                         example: Notch
# %minecraftuuid%:       player's uuid
#                         example: you know what a uuid looks like
# %discordid%:           linked discord account's id
#                         example: 12345678901234567890
# %discordname%:         linked discord account's username
#                         example: Notch
#
# MinecraftDiscordAccountLinkedRoleNameToAddUserTo: the name of a discord role to add a discord user to when they link their account
# MinecraftDiscordAccountLinkedAllowRelinkBySendingANewCode: allows sending a new code to the bot to unlink and relink with the new code
#
MinecraftDiscordAccountLinkedConsoleCommands: ["", "", ""]
MinecraftDiscordAccountUnlinkedConsoleCommands: ["", "", ""]
MinecraftDiscordAccountLinkedRoleNameToAddUserTo: "Linked"
MinecraftDiscordAccountLinkedAllowRelinkBySendingANewCode: false

# Server watchdog
#
# The watchdog constantly monitors the last time your server performed a game tick
# If the time since the last tick goes above the set interval in seconds, Discord messages can be triggered
#
# ServerWatchdogEnabled: whether or not the watchdog is enabled at all
# ServerWatchdogTimeout: time in seconds that need to elapse before the watchdog takes action (Spigot's crash detection uses 60 for this)
#                        the minimum for this value is 10
# ServerWatchdogMessageCount: the amount of times ServerWatchdogMessage is sent. useful if you *really* want to make sure you know something's up
#
ServerWatchdogEnabled: true
ServerWatchdogTimeout: 30
ServerWatchdogMessageCount: 3
